/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package laboratorium.aggigie;

public interface Car{
    boolean needsFuel();
    double getEngineTemperature();
    void driveTo(String destination);
}
